# fly.toml app configuration file generated for autonote on 2024-12-03T15:36:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autonote'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Backend Service
[[services]]
  internal_port = 5174
  protocol = "tcp"
  [[services.ports]]
    port = 5174
  [[services.http_checks]]
    interval = "10s"
    method = "GET"
    path = "/api/health" # Health check
    timeout = "2s"
    grace_period = "1m"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
