# fly.toml app configuration file generated for autonote on 2024-12-03T15:36:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "autonote"
primary_region = "ewr"

[http_service]
  internal_port = 80  # Frontend is served on port 80 by Nginx
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  auto_stop_machines = "off"
  auto_start_machines = false
  internal_port = 5174
  processes = ["app"]
  protocol = "tcp"
  ports = [{ port = "5174" }]